"use strict";
function __export(m) {
    for (var p in m) if (!exports.hasOwnProperty(p)) exports[p] = m[p];
}
Object.defineProperty(exports, "__esModule", { value: true });
/*
 * -----------------------------------------------------------------------------
 * Warning: This file is auto-generated by contracts-gen. Don't edit manually.
 * -----------------------------------------------------------------------------
 */
__export(require("../generated-wrappers/balance_checker"));
__export(require("../generated-wrappers/erc20_bridge_sampler"));
__export(require("../generated-wrappers/fake_taker"));
//# sourceMappingURL=wrappers.js.map