import { TokenAdjacencyGraph } from './types';
export declare const MAINNET_TOKENS: {
    STABLEx: string;
    alUSD: string;
    FRAX: string;
    LUSD: string;
    FEI: string;
    mAAPL: string;
    mSLV: string;
    mIAU: string;
    mAMZN: string;
    mGOOGL: string;
    mTSLA: string;
    mQQQ: string;
    mTWTR: string;
    mMSFT: string;
    mNFLX: string;
    mBABA: string;
    mUSO: string;
    mVIXY: string;
    mLUNA: string;
    WETH: string;
    DAI: string;
    USDC: string;
    USDT: string;
    sUSD: string;
    BUSD: string;
    TUSD: string;
    PAX: string;
    GUSD: string;
    HUSD: string;
    mUSD: string;
    USDN: string;
    dUSD: string;
    USDP: string;
    WBTC: string;
    RenBTC: string;
    sBTC: string;
    tBTC: string;
    hBTC: string;
    pBTC: string;
    bBTC: string;
    oBTC: string;
    aDAI: string;
    aUSDC: string;
    aUSDT: string;
    aSUSD: string;
    MKR: string;
    EURS: string;
    sEUR: string;
    sETH: string;
    stETH: string;
    LINK: string;
    MANA: string;
    KNC: string;
    AAVE: string;
    sLINK: string;
    yUSD: string;
    ybCRV: string;
    yCRV: string;
    bCRV: string;
    yDAI: string;
    yUSDC: string;
    yUSDT: string;
    yTUSD: string;
    crETH: string;
    ankrETH: string;
    vETH: string;
    alETH: string;
    HT: string;
    UST: string;
    MIR: string;
};
export declare const ROPSTEN_TOKENS: {
    WETH: string;
    DAI: string;
    USDC: string;
};
export declare const BSC_TOKENS: {
    WBNB: string;
    BUSD: string;
    USDT: string;
    USDC: string;
    DAI: string;
    PAX: string;
    UST: string;
    WEX: string;
    WETH: string;
};
export declare const POLYGON_TOKENS: {
    DAI: string;
    USDC: string;
    USDT: string;
    amDAI: string;
    amUSDC: string;
    amUSDT: string;
    WBTC: string;
    WMATIC: string;
    WETH: string;
    renBTC: string;
    QUICK: string;
    DFYN: string;
    BANANA: string;
    WEXPOLY: string;
};
export declare const DEFAULT_INTERMEDIATE_TOKENS_BY_CHAIN_ID: {
    1: string[];
    3: string[];
    4: string[];
    42: string[];
    1337: string[];
    56: string[];
    137: string[];
    80001: string[];
};
export declare const DEFAULT_TOKEN_ADJACENCY_GRAPH_BY_CHAIN_ID: {
    1: TokenAdjacencyGraph;
    3: TokenAdjacencyGraph;
    4: TokenAdjacencyGraph;
    42: TokenAdjacencyGraph;
    1337: TokenAdjacencyGraph;
    56: TokenAdjacencyGraph;
    137: TokenAdjacencyGraph;
    80001: TokenAdjacencyGraph;
};
export declare const WRAPPED_NETWORK_TOKEN_BY_CHAIN_ID: {
    1: string;
    3: string;
    4: string;
    42: string;
    1337: string;
    56: string;
    137: string;
    80001: string;
};
//# sourceMappingURL=tokens.d.ts.map