import { ContractArtifact } from 'ethereum-types';
export declare const artifacts: {
    ApproximateBuys: ContractArtifact;
    BalancerSampler: ContractArtifact;
    CurveSampler: ContractArtifact;
    ERC20BridgeSampler: ContractArtifact;
    Eth2DaiSampler: ContractArtifact;
    KyberSampler: ContractArtifact;
    LiquidityProviderSampler: ContractArtifact;
    MStableSampler: ContractArtifact;
    MultiBridgeSampler: ContractArtifact;
    NativeOrderSampler: ContractArtifact;
    SamplerUtils: ContractArtifact;
    TwoHopSampler: ContractArtifact;
    UniswapSampler: ContractArtifact;
    UniswapV2Sampler: ContractArtifact;
    IBalancer: ContractArtifact;
    ICurve: ContractArtifact;
    IEth2Dai: ContractArtifact;
    IKyberHintHandler: ContractArtifact;
    IKyberNetwork: ContractArtifact;
    IKyberNetworkProxy: ContractArtifact;
    IKyberStorage: ContractArtifact;
    ILiquidityProvider: ContractArtifact;
    ILiquidityProviderRegistry: ContractArtifact;
    IMStable: ContractArtifact;
    IMultiBridge: ContractArtifact;
    IUniswapExchangeQuotes: ContractArtifact;
    IUniswapV2Router01: ContractArtifact;
    DummyLiquidityProvider: ContractArtifact;
    DummyLiquidityProviderRegistry: ContractArtifact;
    TestERC20BridgeSampler: ContractArtifact;
    TestNativeOrderSampler: ContractArtifact;
};
//# sourceMappingURL=artifacts.d.ts.map