"use strict";
function __export(m) {
    for (var p in m) if (!exports.hasOwnProperty(p)) exports[p] = m[p];
}
Object.defineProperty(exports, "__esModule", { value: true });
/*
 * -----------------------------------------------------------------------------
 * Warning: This file is auto-generated by contracts-gen. Don't edit manually.
 * -----------------------------------------------------------------------------
 */
__export(require("../test/generated-wrappers/balancer_bridge"));
__export(require("../test/generated-wrappers/chai_bridge"));
__export(require("../test/generated-wrappers/curve_bridge"));
__export(require("../test/generated-wrappers/dex_forwarder_bridge"));
__export(require("../test/generated-wrappers/dydx_bridge"));
__export(require("../test/generated-wrappers/erc1155_proxy"));
__export(require("../test/generated-wrappers/erc20_bridge_proxy"));
__export(require("../test/generated-wrappers/erc20_proxy"));
__export(require("../test/generated-wrappers/erc721_proxy"));
__export(require("../test/generated-wrappers/eth2_dai_bridge"));
__export(require("../test/generated-wrappers/i_asset_data"));
__export(require("../test/generated-wrappers/i_asset_proxy"));
__export(require("../test/generated-wrappers/i_asset_proxy_dispatcher"));
__export(require("../test/generated-wrappers/i_authorizable"));
__export(require("../test/generated-wrappers/i_balancer_pool"));
__export(require("../test/generated-wrappers/i_chai"));
__export(require("../test/generated-wrappers/i_chainlink_oracle"));
__export(require("../test/generated-wrappers/i_curve"));
__export(require("../test/generated-wrappers/i_dydx"));
__export(require("../test/generated-wrappers/i_dydx_bridge"));
__export(require("../test/generated-wrappers/i_erc20_bridge"));
__export(require("../test/generated-wrappers/i_eth2_dai"));
__export(require("../test/generated-wrappers/i_gas_token"));
__export(require("../test/generated-wrappers/i_kyber_network_proxy"));
__export(require("../test/generated-wrappers/i_uniswap_exchange"));
__export(require("../test/generated-wrappers/i_uniswap_exchange_factory"));
__export(require("../test/generated-wrappers/i_uniswap_v2_router01"));
__export(require("../test/generated-wrappers/kyber_bridge"));
__export(require("../test/generated-wrappers/mixin_asset_proxy_dispatcher"));
__export(require("../test/generated-wrappers/mixin_authorizable"));
__export(require("../test/generated-wrappers/mixin_gas_token"));
__export(require("../test/generated-wrappers/multi_asset_proxy"));
__export(require("../test/generated-wrappers/ownable"));
__export(require("../test/generated-wrappers/ritual_bridge"));
__export(require("../test/generated-wrappers/static_call_proxy"));
__export(require("../test/generated-wrappers/test_chai_bridge"));
__export(require("../test/generated-wrappers/test_dex_forwarder_bridge"));
__export(require("../test/generated-wrappers/test_dydx_bridge"));
__export(require("../test/generated-wrappers/test_erc20_bridge"));
__export(require("../test/generated-wrappers/test_eth2_dai_bridge"));
__export(require("../test/generated-wrappers/test_kyber_bridge"));
__export(require("../test/generated-wrappers/test_oracle"));
__export(require("../test/generated-wrappers/test_ritual_bridge"));
__export(require("../test/generated-wrappers/test_static_call_target"));
__export(require("../test/generated-wrappers/test_uniswap_bridge"));
__export(require("../test/generated-wrappers/test_uniswap_v2_bridge"));
__export(require("../test/generated-wrappers/uniswap_bridge"));
__export(require("../test/generated-wrappers/uniswap_v2_bridge"));
//# sourceMappingURL=wrappers.js.map